image: registry.gitlab.com/quarto-forge/docker/rstats

website:
  script:
    - sudo apt-get install libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
    - Rscript -e "options(repos = c(CRAN = 'https://cran.rstudio.com')); install.packages('pak'); pak::pak()"
    - quarto render
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - main
