image: rocker/tidyverse

pages:
    script:
      - R -e "remotes::install_deps()"
      - R -e "bookdown::render_book('index.Rmd')"
    artifacts:
        paths:
            - public
        expire_in: 1 hour
    only:
        - main
