# Background and rationale {#background}

Early life adversity is known to influence the risk for chronic cardiometabolic
diseases such as type 2 diabetes (T2D) in later adulthood. Early life, typically
defined from conception until early childhood (~6 years), is a period
characterised by substantial growth and development that can establish an
individual's metabolic capacity for the rest of their life
[@Hales2001;@Gluckman2007]. Extreme periods of or consistent exposure to
adversity, such as poverty, malnutrition, or famine, can set individuals on a
higher disease risk trajectory
[@Hales2001;@Li2011a;@Clarkin2012;@McEniry2013;@Berens2017a]. For instance,
exposure to famine during early life can increase the risk of developing T2D by
about 60% [@Abeelen2012a]. While extreme early life adversity is relatively
uncommon in contemporary European populations, some immigrants and refugees have
been exposed to more extreme conditions (e.g. refugees from conflict-ridden
Syria). Even less extreme adversity, such as neglect, loss of a parent, or
childhood conflict, can increase the risk for diseases such as T2D
[@Maniam2014a]. For instance, neglect and emotional abuse can increase the risk
of obesity, a strong determinant of T2D, by up to 50% [@Thomas2008a]. These forms
of adversity are much more common in many EU countries, with nearly 30% of EU
children experiencing some form of mental or physical abuse [@Europe2014a].

Much of the literature on early life origins of disease come from a few birth cohorts
[@Solis2016a;@Whitley2008a;@Skidmore2007;@Eriksson2011;@Ekelund2007a;@Azad2012a;@Chaparro2014a]
or is based on inferences from cross-sectional studies, animal models, or "natural"
experiments (e.g the Dutch Hunger Winter, a period of famine during the Nazi
occupation of the Netherlands)
[@Schulz2010a;@Zheng2012a;@Carroll2013a;@Han2015a]. However, limited studies
have investigated how early life adversity mediates its influence on later
disease through adult metabolic capacity (such as through lipid metabolism,
inflammatory processes, and/or glucose regulation; hypothetical pathways are
shown in Figure 1) [@Berens2017a]. A key component to efficient identification,
prevention, and management of T2D risk is knowledge on these specific mechanisms
involved in the pathogenesis of T2D and which mechanism to target to mitigate
risk. The few studies on this topic, mainly cross-sectional and/or self-report
of early life, have found that early life socioeconomic position and childhood
experiences such as neglect associate with a lower composite score of metabolic
capacity [@Solis2016a;@Solis2015a;@Robertson2014a;@Kumari2012a;@Gruenewald2012a].

The increasing availability of "big data" offers powerful alternatives to costly
birth cohorts and can fill important knowledge gaps. For example, in the
Scandinavian countries a wide range of medical and socioeconomic data has been
recorded in national citizen registry databases over several decades
[@Pedersen2011a]. Data from these registries can in turn be linked to sources of
data that contain metabolic phenotyping (e.g. in cohorts). However,
appropriately dealing with this structure and scale of data is challenging from
conceptual, analytical, and computational perspectives. Analytic methods for
dealing with this type of complicated data are being developed but are not yet
fully implemented. Causal reasoning, an area of active development in
epidemiology [@Pearl2010b;@Richmond2014a;@laBastide-vanGemert2014a], and pathway
(mediation) analysis techniques are methods that, with some adjustments, have
the potential to fully exploit these complex, high-dimensional datasets.
